### ISSUE TITLE
time needed to run the image

### ISSUE THREAD

**Issue by miriampol2c** [morcoslab/LGL-VAE#1]
hi,

What a nice work! I would like to use your approach to classify my sequences.
But... how long does it take to run the image with docker run -p 5006:5006 -v <directory to save files to>:/docker lgl_vae?
I've been trying it for a while and it just hangs (without GPUs) :(

**Comment by ceziegler** [comment]
Hello, depending on the number of sequences it generally takes about 6-8 hours. You can also train the model without the GUI using scripts/run_vae and then finish the analysis using the GUI, just be sure to mount the directory where the model is stored.
